routes/web.php
    $file_path = public_path() .'/files/'. $filename;

    if (file_exists($file_path)){
        // Send Download
        return Response::download($file_path, $filename, [
            'Content-Length: '. filesize($file_path)
        ]);
    }else{
        // Error
        return redirect()->back()->withErrors('Requested file does not exist on our server!');
    }
}) ->where('filename', '[A-Za-z0-9\-\_\.]+');

Route::group(['middleware' => 'guest'], function () {
	/*Route::get('/resend-activation','UserController@resendActivation');
	Route::post('/resend-activation',array('as' => 'user.resend-activation','uses' => 'UserController@postResendActivation'));
	Route::get('/activate-account/{token}','UserController@activateAccount');

	Route::get('/auth/{provider}', 'SocialLoginController@providerRedirect');
    Route::get('/auth/{provider}/callback', 'SocialLoginController@providerRedirectCallback');

	Route::get('/verify-purchase', 'AccountController@verifyPurchase');
	Route::post('/verify-purchase', 'AccountController@postVerifyPurchase');
	Route::resource('/install', 'AccountController',['only' => ['index', 'store']]);
	Route::get('/update','AccountController@updateApp');
	Route::post('/update',array('as' => 'update-app','uses' => 'AccountController@postUpdateApp'));*/
});

Auth::routes();

	/*Route::group(['middleware' => ['auth','web','account']],function(){
		Route::get('/verify-security','UserController@verifySecurity');
		Route::post('/verify-security',array('as' => 'user.verify-security','uses' => 'UserController@postVerifySecurity'));
	});*/

Route::group(['middleware' => ['auth','web','account','two_factor_auth','lock_screen','maintenance_mode']], function () {

	Route::get('/oauth/authorize',function(){
		return view('authorize');
	});

	#Route::get('/release-license','AccountController@releaseLicense');
	#Route::get('/check-update','AccountController@checkUpdate');
	Route::get('/home', 'HomeController@index');
	Route::post('/template/content','TemplateController@content',['middleware' => ['permission:enable_email_template']]);

	Route::get('/set-language/{locale}','LanguageController@setLanguage',['middleware' => ['permission:change-language']]);

	Route::group(['middleware' => ['permission:manage-email-log']], function () {
		Route::model('email','\App\Email');
		Route::post('/email/lists','EmailController@lists');
		Route::resource('/email', 'EmailController',['only' => ['index','show']]);
	});

	Route::group(['middleware' => ['permission:manage-configuration']], function() {
		Route::get('/configuration', 'ConfigurationController@index');
		Route::post('/configuration',array('as' => 'configuration.store','uses' => 'ConfigurationController@store'));
		Route::post('/configuration-logo',array('as' => 'configuration.logo','uses' => 'ConfigurationController@logo'));
		Route::post('/configuration-mail',array('as' => 'configuration.mail','uses' => 'ConfigurationController@mail'));
		Route::post('/configuration-sms',array('as' => 'configuration.sms','uses' => 'ConfigurationController@sms'));
	});

	Route::group(['middleware' => ['permission:manage-template']], function() {
		Route::model('template','\App\Template');
		Route::post('/template/lists','TemplateController@lists');
		Route::resource('/template', 'TemplateController');
	});

	Route::group(['middleware' => ['permission:manage-message']], function() {
		Route::get('/message', 'MessageController@index');
		Route::post('/load-message','MessageController@load');
		Route::post('/message/{type}/lists','MessageController@lists');
		Route::get('/message/forward/{token}','MessageController@forward');
		Route::post('/message', ['as' => 'message.store', 'uses' => 'MessageController@store']);
		Route::post('/message-reply/{id}', ['as' => 'message.reply', 'uses' => 'MessageController@reply']);
		Route::post('/message-forward/{token}', ['as' => 'message.post-forward', 'uses' => 'MessageController@postForward']);
		Route::get('/message/{token}/download','MessageController@download');
		Route::post('/message/starred','MessageController@starred');
		Route::get('/message/{token}', array('as' => 'message.view', 'uses' => 'MessageController@view'));
		Route::delete('/message/{id}/trash', array('as' => 'message.trash', 'uses' => 'MessageController@trash'));
		Route::post('/message/restore', array('as' => 'message.restore', 'uses' => 'MessageController@restore'));
		Route::delete('/message/{id}/delete', array('as' => 'message.destroy', 'uses' => 'MessageController@destroy'));
	});

	Route::group(['middleware' => ['permission:manage-todo']], function() {
		Route::model('todo','\App\Todo');
		Route::resource('/todo', 'TodoController');
	});

	Route::group(['middleware' => ['permission:manage-language']], function() {
		Route::post('/language/lists','LanguageController@lists');
		Route::resource('/language', 'LanguageController');
		Route::post('/language/addWords',array('as'=>'language.add-words','uses'=>'LanguageController@addWords'));
		Route::patch('/language/plugin/{locale}',array('as'=>'language.plugin','uses'=>'LanguageController@plugin'));
		Route::patch('/language/updateTranslation/{id}', ['as' => 'language.update-translation','uses' => 'LanguageController@updateTranslation']);
	});

	Route::group(['middleware' => ['permission:manage-backup']], function() {
		Route::model('backup','\App\Backup');
		Route::post('/backup/lists','BackupController@lists');
		Route::resource('/backup', 'BackupController',['only' => ['index','show','store','destroy']]);
	});

	Route::group(['middleware' => ['permission:manage-ip-filter']], function() {
		Route::model('ip_filter','\App\IpFilter');
		Route::post('/ip-filter/lists','IpFilterController@lists');
		Route::resource('/ip-filter', 'IpFilterController');
	});

	Route::group(['middleware' => ['permission:manage-custom-field']], function() {
		Route::model('custom_field','\App\CustomField');
		Route::post('/custom-field/lists','CustomFieldController@lists');
		Route::resource('/custom-field', 'CustomFieldController');
	});

	Route::group(['middleware' => ['permission:manage-role']], function() {
		Route::model('role','\App\Role');
		Route::post('/role/lists','RoleController@lists');
		Route::resource('/role', 'RoleController');
	});

	Route::group(['middleware' => ['permission:manage-permission']], function() {
		Route::model('permission','\App\Permission');
		Route::post('/permission/lists','PermissionController@lists');
		Route::resource('/permission', 'PermissionController');
		Route::get('/save-permission','PermissionController@permission');
		Route::post('/save-permission',array('as' => 'permission.save-permission','uses' => 'PermissionController@savePermission'));
	});

	Route::model('chat','\App\Chat');
	Route::resource('/chat', 'ChatController',['only' => 'store']);
	Route::post('/fetch-chat','ChatController@index');

	Route::get('/lock','HomeController@lock');
	Route::post('/lock',array('as' => 'unlock','uses' => 'HomeController@unlock'));

	Route::group(['middleware' => ['feature_available:enable_activity_log']],function() {
		Route::get('/activity-log','HomeController@activityLog');
		Route::post('/activity-log/lists','HomeController@activityLogList');
	});

	//corporate
	Route::model('corporate','\App\Corporate');
	Route::post('/corporate/lists','CorporateController@lists');
	Route::resource('/corporate', 'CorporateController');
	Route::post('/corporate/profile-update/{id}',array('as' => 'corporate.profile-update','uses' => 'CorporateController@profileUpdate'));
	Route::post('/corporate/avatar/{id}',array('as' => 'corporate.avatar','uses' => 'CorporateController@avatar'));
	Route::post('/corporate/custom-field-update/{id}',array('as' => 'corporate.custom-field-update','uses' => 'CorporateController@customFieldUpdate'));
	Route::get('/division/create/{id}','CorporateController@addDivision');
	Route::post('/division-add','CorporateController@addNewDivision');


	//simulasi
	Route::get('/survey/{slug}/{section}/{simulasi}', 'SurveyController@getSimulasi');

	//user
	Route::model('user','\App\User');
	Route::get('/user/history/{user_id}', 'SurveyController@get_project_diassign');
	Route::get('/user/history/{slug}/{user_id}', 'SurveyController@get_tools_diassign');
	Route::post('/user/lists','UserController@lists');
	Route::post('/user/reset-password/{user_id}','UserController@updatePassword');
	Route::get('/user/reset',function(){
		return view('user.update-password');
	});
	Route::post('/user/profile-update/{id}',array('as' => 'user.profile-update','uses' => 'UserController@profileUpdate'));
	Route::post('/user/social-update/{id}',array('as' => 'user.social-update','uses' => 'UserController@socialUpdate'));
	Route::post('/user/custom-field-update/{id}',array('as' => 'user.custom-field-update','uses' => 'UserController@customFieldUpdate'));
	Route::post('/user/avatar/{id}',array('as' => 'user.avatar','uses' => 'UserController@avatar'));
	Route::post('/change-user-status','UserController@changeStatus');
	Route::post('/force-change-user-password/{user_id}',array('as' => 'user.force-change-password','uses' => 'UserController@forceChangePassword'));
	Route::get('/change-password', 'UserController@changePassword');
	Route::post('/change-password',array('as'=>'change-password','uses' =>'UserController@doChangePassword'));
	Route::post('/user/email/{id}',array('as' => 'user.email', 'uses' => 'UserController@email'));

	// upload user Excel
	Route::get('/user/upload', 'UploaduserController@index');
	Route::get('/format-excel', 'UploaduserController@downloadFormat');
	Route::get('/format-excel-add-user', 'UploaduserController@downloadFormatAdd');
	Route::post('/upload-user', 'UploaduserController@upload');
	//end upload excel

	//backend route
	Route::get('backend/history', 'BackendController@history');
	Route::get('backend/report/{slug}', 'BackendController@reportUserBySurvey');
	Route::get('backend/detail-peserta-survey/{slug}', 'BackendController@getPesertaSurvey');

app/Message.php
<?php
namespace App;
use Eloquent;

class Message extends Eloquent {

	protected $fillable = [
							'from_user_id',
							'to_user_id',
							'subject',
							'body',
							'attachments',
							'is_read',
							'reply_id',
							'delete_sender',
							'delete_receiver',
						];
	protected $primaryKey = 'id';
	protected $table = 'messages';

    public function userTo()
    {
        return $this->belongsTo('App\User','to_user_id'); 
    }

    public function userFrom()
    {
        return $this->belongsTo('App\User','from_user_id'); 
    }

    public function replies(){
    	return $this->hasMany('App\Message','reply_id');
    }

    public function reply()
    {
        return $this->belongsTo('App\Message','reply_id'); 
    }
}

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use HasApiTokens,Notifiable,EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password','username','status','custom_token'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function profile()
    {
        return $this->hasOne('App\Profile');
    }

    public function getFullNameAttribute(){
        return $this->Profile->first_name.' '.$this->Profile->last_name;
    }

    public function routeNotificationForNexmo()
    {
        return $this->Profile->mobile;
    }

    public function corporate()
    {
        return $this->belongsTo('App\Corporate', 'corp_id');
    }

    public function user_project()
    {
        return $this->hasMany('App\UserProject', 'id_user');
    }
}

resources/views/message/forward.blade.php
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
		<h4 class="modal-title">Forward</h4>
	</div>
	<div class="modal-body">
		<div class="row">
			<div class="col-md-12">
				{!! Form::model($message,['files'=>'true','method' => 'POST','route' => ['message.post-forward',$message->token] ,'class' => 'forward-form','id' => 'forward-form']) !!}
					<div class="form-group">
						{!! Form::select('to_user_id', $users, '',['class'=>'form-control input-xlarge select2me','placeholder'=>trans('messages.select_one'),'style' => 'width:100%;'])!!}
					</div>
					<div class="form-group">
						{!! Form::input('text','subject','Fw: '.$message->subject,['class'=>'form-control','placeholder'=>trans('messages.subject')])!!}
					</div>
					<div class="form-group">
						{!! Form::textarea('body',$message->body,['class' => 'form-control summernote', 'placeholder' => trans('messages.body')])!!}
					</div>
					@if($message->attachments)
						<p><i class="fa fa-paperclip"></i> <a href="/message/{{$message->token}}/download">{{$message->attachments}}</a></p>
					@endif
					<div class="form-group">
						<button type="submit" class="btn btn-success btn-sm pull-right"><i class="fa fa-paper-plane"></i> {!! trans('messages.send') !!}</button>
					</div>	
				{!! Form::close() !!}
			</div>
		</div>
	</div>

resources/views/message/index.blade.php
@extends('layouts.default')

	@section('breadcrumb')
		<div class="row">
			<ul class="breadcrumb">
			    <li><a href="/home">{!! trans('messages.home') !!}</a></li>
			    <li class="active">Message</li>
			</ul>
		</div>
	@stop
	
	@section('content')
		<div class="row">
			<div class="col-sm-2">
			    <ul class="nav nav-tabs tabs-left">
				  <li><a href="#compose-tab" data-toggle="tab"><i class="fa fa-pencil-square"></i> Compose</a></li>
			      <li class="active"><a href="#inbox-tab" data-toggle="tab"><i class="fa fa-inbox"></i> Inbox ({{$count_inbox}})</a></li>
				  <li><a href="#sent-tab" data-toggle="tab"><i class="fa fa-share"></i> Sent</a></li>
				  <li><a href="#starred-tab" data-toggle="tab"><i class="fa fa-star"></i> Starred</a></li>
				  <li><a href="#trash-tab" data-toggle="tab"><i class="fa fa-trash"></i> Trash</a></li>
			    </ul>
			</div>
			<div class="col-sm-10">
			    <div class="tab-content">
			      	<div class="tab-pane active" id="inbox-tab">
						<div class="panel panel-default">
							<div class="panel-heading">
                    			<strong>Inbox</strong>
                    		</div>
                    		<div class="panel-body full">
                    			<div class="row">
                    				<div class="col-md-12">
										@include('common.datatable',['table' => $table_data['inbox-table']])
									</div>
								</div>
                    		</div>
                    	</div>
                    </div>
			      	<div class="tab-pane" id="sent-tab">
						<div class="panel panel-default">
							<div class="panel-heading">
                    			<strong>Sent</strong>
                    		</div>
                    		<div class="panel-body full">
                    			<div class="row">
                    				<div class="col-md-12">
										@include('common.datatable',['table' => $table_data['sent-table']])
									</div>
								</div>
                    		</div>
                    	</div>
                    </div>
			      	<div class="tab-pane" id="starred-tab">
						<div class="panel panel-default">
							<div class="panel-heading">
                    			<strong>Starred</strong>
                    		</div>
                    		<div class="panel-body full">
                    			<div class="row">
                    				<div class="col-md-12">
										@include('common.datatable',['table' => $table_data['starred-table']])
									</div>
								</div>
                    		</div>
                    	</div>
                    </div>
			      	<div class="tab-pane" id="trash-tab">
						<div class="panel panel-default">
							<div class="panel-heading">
                    			<strong>Trash</strong>
                    		</div>
                    		<div class="panel-body full">
                    			<div class="row">
                    				<div class="col-md-12">
										@include('common.datatable',['table' => $table_data['trash-table']])
									</div>
								</div>
                    		</div>
                    	</div>
                    </div>
			      	<div class="tab-pane" id="compose-tab">
						<div class="panel panel-default">
							<div class="panel-heading">
                    			<strong>Compose</strong>
                    		</div>
                    		<div class="panel-body">
                    			{!! Form::open(['files'=>'true','route' => 'message.store','role' => 'form', 'class'=>'compose-form','id' => 'compose-form','data-submit' => 'noAjax']) !!}
									<div class="form-group">
										{!! Form::select('to_user_id', $users, '',['class'=>'form-control input-xlarge select2me','placeholder'=>trans('messages.select_one'),'style' => 'width:100%;'])!!}
									</div>
									<div class="form-group">
										{!! Form::input('text','subject','',['class'=>'form-control','placeholder'=>trans('messages.subject')])!!}
									</div>
									<div class="form-group">
										{!! Form::textarea('body','',['class' => 'form-control summernote', 'placeholder' => trans('messages.body')])!!}
									</div>
									<div class="form-group">
										<input type="file" name="file" id="file" class="fileinput" title="{!! trans('messages.select').' '.trans('messages.attachment') !!}">
									</div>
									<div class="form-group">
										<div class="pull-right">
											<button type="submit" name="submit" class="btn btn-success btn-sm"><i class="fa fa-paper-plane"></i> {!! trans('messages.send') !!}</button>
										</div>
									</div>	
								{!! Form::close() !!}
                    		</div>
                    	</div>
                    </div>
                </div>
            </div>
        </div>
    @stop

resources/views/message/load.blade.php
	{!! getAvatar($message->from_user_id,45) !!}
		<div style="float:left;margin-left:10px;margin-bottom: 20px;">
		<strong class="primary-font">{{$message->UserFrom->full_name}}</strong> 
		<a href="#" data-source="/message/starred" data-extra="&token={{$message->token}}" data-ajax="1" data-refresh="load-message">
			@if((Auth::user()->id == $message->from_user_id && $message->is_starred_sender) || (Auth::user()->id == $message->to_user_id && $message->is_starred_receiver))
				<i class="fa fa-star fa-lg starred"></i>
			@else
				<i class="fa fa-star-o fa-lg starred"></i>
			@endif
		</a>
		<br />
		{{showDateTime($message->created_at)}}
	</div>
	
	<div class="pull-right">
		<div class="btn-group btn-group-xs">
			<a href="#" data-href="/message/forward/{{$message->token}}" data-target="#myModal" data-toggle="modal" class="btn btn-default btn-xs">
				<i class="fa fa-share"></i>
			</a>
			{!! delete_form(['message.trash',$message->id],['refresh' => 'load-message','ajax' => 'noAjax']) !!}
		</div>
	</div>

	<div class="clearfix"></div>
	{!!$message->body!!}
	@if($message->attachments)
		<p><i class="fa fa-paperclip"></i> <a href="/message/{{$message->token}}/download">{{$message->attachments}}</a></p>
	@endif

	@foreach($replies as $reply)
		<div style="border-bottom:1px solid #f5f5f5;margin: 15px 0px;"></div>
		<div style="margin-left:30px;" name="{{$reply->token}}">
		{!! getAvatar($reply->from_user_id,45) !!}
		<div style="float:left;margin-left:10px;margin-bottom: 20px;">
			<strong class="primary-font">{{$reply->UserFrom->full_name}}</strong> 
			<a href="#" data-source="/message/starred" data-extra="&token={{$reply->token}}"  data-ajax="1" data-refresh="load-message">
				@if((Auth::user()->id == $reply->from_user_id && $reply->is_starred_sender) || (Auth::user()->id == $reply->to_user_id && $reply->is_starred_receiver))
					<i class="fa fa-star fa-lg starred"></i>
				@else
					<i class="fa fa-star-o fa-lg starred"></i>
				@endif
			</a>	
			<br />
			{{showDateTime($reply->created_at)}}
		</div>
		<div class="pull-right">
			<div class="btn-group btn-group-xs">
				<a href="#" data-href="/message/forward/{{$reply->token}}" data-target="#myModal" data-toggle="modal" class="btn btn-default btn-xs">
					<i class="fa fa-share"></i>
				</a>
				{!! delete_form(['message.trash',$reply->id],['refresh' => 'load-message']) !!}
			</div>
		</div>
		<div class="clearfix"></div>
		{!!$reply->body!!}
		@if($reply->attachments)
			<p><i class="fa fa-paperclip"></i> <a href="/message/{{$reply->token}}/download">{{$reply->attachments}}</a></p>
		@endif
		</div>
	@endforeach

resources/views/message/view.blade.php
@extends('layouts.default')

	@section('breadcrumb')
		<div class="row">
			<ul class="breadcrumb">
			    <li><a href="/home">{!! trans('messages.home') !!}</a></li>
			    <li><a href="/message">{!! trans('messages.message') !!}</a></li>
			    <li class="active">{{$message->subject}}</li>
			</ul>
		</div>
	@stop
	
	@section('content')
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
            			<strong>{{$message->subject}}</strong>
            		</div>
            		<div class="panel-body">

            			<div id="load-message" data-token="{{$message->token}}"></div>

            			<div style="border-bottom:1px solid #f5f5f5;margin: 15px 0px;"></div>
            			<div style="margin-left:30px;margin-top:20px;">
            				<p style="font-weight: bold;font-size: 15px;">Send Reply</p>
            				{!! Form::model($message,['files'=>'true','method' => 'POST','route' => ['message.reply',$message->id] ,'class' => 'reply-form','id' => 'reply-form','data-refresh' => 'load-message']) !!}
								<div class="form-group">
									{!! Form::textarea('body','',['class' => 'form-control summernote', 'placeholder' => trans('messages.body')])!!}
								</div>
								<div class="form-group">
									<input type="file" name="file" id="file" class="fileinput" title="{!! trans('messages.select').' '.trans('messages.attachment') !!}">
								</div>
								<div class="form-group">
									<button type="submit" class="btn btn-success btn-sm pull-right"><i class="fa fa-paper-plane"></i> {!! trans('messages.send') !!}</button>
								</div>	
							{!! Form::close() !!}
						</div>
            		</div>
            	</div>
			</div>
		</div>
	@stop